Repository YunoHost/yunohost-admin, pull requests merged in 2018-08, with the labels that each got.

#203 Remove forgotten console.log
  src/js/yunohost/controllers/home.js
Labels: micro decision

#202 Log 'xhr' variable in console when an unexpected error occur
  src/js/yunohost/helpers.js
Labels: micro decision, ready to merge

#130 Web interface for journal new features
  src/bower.json
  src/css/style.less
  src/gulpfile.js
  src/js/yunohost/controllers/tools.js
  src/js/yunohost/helpers.js
  src/js/yunohost/main.js
  src/locales/en.json
  src/views/tools/tools_list.ms
  src/views/tools/tools_log.ms
  src/views/tools/tools_logs.ms
  src/views/tools/tools_rebooting.ms
  src/views/tools/tools_shuttingdown.ms
Labels: opinion needed, small decision
