Repository YunoHost/yunohost-admin, pull requests merged in 2019-06, with the labels that each got.

#246 display the current version of the app
  src/views/app/app_info.ms
Labels: ready to merge

#245 Set minlength/maxlength on admin password form
  src/views/postinstall/postinstall_3.ms
Labels: ready to merge

#244 [enh] Convert ascii progress bars to bootstrap progress bar
  src/css/style.less
  src/js/yunohost/helpers.js
Labels: ready to merge

#242 High quality apps and maintained states
  src/css/style.less
  src/js/yunohost/controllers/apps.js
  src/locales/en.json
  src/views/app/app_install.ms
  src/views/app/app_list_install.ms
Labels: medium decision, ready to merge

#248 [mod] Move applist management to Tools section
  src/js/yunohost/controllers/apps.js
  src/js/yunohost/controllers/tools.js
  src/locales/en.json
  src/views/app/app_list_install.ms
  src/views/tools/tools_appslists_info.ms
  src/views/tools/tools_appslists_list.ms
  src/views/tools/tools_list.ms
  src/views/tools/tools_versions.ms
Labels: medium decision, opinion needed, ready to merge
