Repository YunoHost/yunohost-admin, pull requests merged in 2019-11, with the labels that each got.

#271 Remove app debug button, follow-up of corresponding PR on yunohost core
  src/js/yunohost/controllers/apps.js
  src/locales/en.json
  src/views/app/app_debug.ms
  src/views/app/app_info.ms
Labels: ready to merge

#263 Remove the whole monitoring / glances stuff
  src/js/yunohost/controllers/monitor.js
  src/locales/en.json
  src/views/tools/tools_list.ms
  src/views/tools/tools_monitoring.ms
Labels: ready to merge

#260 [mod] rename parameters according to changes in cli/core for ux
  src/js/yunohost/controllers/domains.js
Labels: ready to merge

#262 Code refactoring, readability improvements, use buttons instead of links when it's not about changing page
  src/css/style.less
  src/index.html
  src/js/yunohost/controllers/apps.js
  src/js/yunohost/controllers/backup.js
  src/js/yunohost/controllers/domains.js
  src/js/yunohost/controllers/firewall.js
  src/js/yunohost/controllers/home.js
  src/js/yunohost/controllers/postinstall.js
  src/js/yunohost/controllers/services.js
  src/js/yunohost/controllers/tools.js
  src/js/yunohost/controllers/users.js
  src/js/yunohost/events.js
  src/js/yunohost/filters.js
  src/js/yunohost/helpers.js
  src/js/yunohost/main.js
  src/locales/en.json
  src/views/app/app_info.ms
  src/views/backup/backup.ms
  src/views/backup/backup_info.ms
  src/views/backup/storage_create.ms
  src/views/domain/domain_cert.ms
  src/views/domain/domain_info.ms
  src/views/service/service_info.ms
  src/views/tools/tools_firewall.ms
  src/views/tools/tools_log.ms
  src/views/tools/tools_logs.ms
  src/views/tools/tools_migrations.ms
  src/views/tools/tools_reboot.ms
  src/views/tools/tools_rebooting.ms
  src/views/tools/tools_shuttingdown.ms
  src/views/tools/tools_update.ms
  src/views/upgrade/upgrade.ms
  src/views/user/group_list.ms
  src/views/user/user_info.ms
Labels: ready to merge

#209 [enh] New diagnosis interface
  src/css/style.less
  src/js/yunohost/controllers/diagnosis.js
  src/js/yunohost/controllers/tools.js
  src/js/yunohost/events.js
  src/js/yunohost/helpers.js
  src/js/yunohost/main.js
  src/locales/en.json
  src/views/diagnosis/diagnosis_show.ms
  src/views/home.ms
  src/views/tools/tools_diagnosis.ms
  src/views/tools/tools_list.ms
  src/views/tools/tools_update.ms
Labels: medium decision, opinion needed, ready to merge, test needed

#264 Remove the appslist system from the webadmin
  src/js/yunohost/controllers/tools.js
  src/locales/en.json
  src/views/tools/tools_appslists_info.ms
  src/views/tools/tools_appslists_list.ms
  src/views/tools/tools_list.ms
Labels: ready to merge

#207 [fix] Try something to be independent from github
  src/js/yunohost/controllers/apps.js
  src/views/app/app_list_install.ms
Labels: small decision, work needed

#274 Update service view
  src/js/yunohost/controllers/services.js
  src/js/yunohost/helpers.js
  src/locales/en.json
  src/views/service/service_info.ms
  src/views/service/service_list.ms
  src/views/service/service_log.ms
Labels: ready to merge
